# Occupational Map

## Intro

Goal: Use PCA to create an interactive map showing similarities between different occupations to help people explore career opportunities.

dataset source: https://www.onetcenter.org/database.html#all-files

## EDA

In [1]:
import pandas as pd

Our dataset is comprised of many tables, each pertaining to a different measure of components that make up each occupation. Lets just start by looking at one of these files:

In [2]:
knowledge = pd.read_excel('db_28_2_excel/Knowledge.xlsx')

In [3]:
knowledge.head()

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.C.1.a,Administration and Management,IM,Importance,4.78,28.0,0.1102,4.5564,5.0000,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,2.C.1.a,Administration and Management,LV,Level,6.50,28.0,0.2130,6.0666,6.9409,N,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,2.C.1.b,Administrative,IM,Importance,2.42,28.0,0.4651,1.4662,3.3749,N,NaN,08/2023,Incumbent
3,11-1011.00,Chief Executives,2.C.1.b,Administrative,LV,Level,2.69,28.0,0.8678,0.9078,4.4690,N,N,08/2023,Incumbent
4,11-1011.00,Chief Executives,2.C.1.c,Economics and Accounting,IM,Importance,4.04,28.0,0.3480,3.3246,4.7526,N,NaN,08/2023,Incumbent

The key metric here is the 'Data Value' for each 'Element Name'/'Element ID', 'Scale Name'/'Scale ID' combination. These metrics will form our vectors such that each row will be a single 'O*NET-SOC Code' and each colum a separate metric. Lets bring in our other data and merge them together to create our working dataset:

In [16]:
# first specify which datasets we want to import (all datasets that contain a 'Data Value' metric)
df_names = ['Knowledge', 
            'Skills', 
            'Abilities', 
            'Education, Training, and Experience', 
            'Interests', 
            'Work Values', 
            'Work Styles',
            'Work Activities',
            'Work Context']

# NOTE from pandas documentation:
# concat() makes a full copy of the data, and iteratively reusing concat() can create unnecessary copies. 
# Collect all DataFrame or Series objects in a list before using concat().

df_list = [] # create empty list to store df's

# iterate through our list of datasets
for df_name in df_names:
    df = pd.read_excel(f'db_28_2_excel/{df_name}.xlsx') # read into a temp df
    df = df[['O*NET-SOC Code', 'Element ID', 'Scale ID', 'Data Value']] # pull out pertinent cols
    df_list.append(df) # append to list of df's
    
df = pd.concat(df_list)
df.head()

  O*NET-SOC Code             Title Element ID Scale ID  Data Value
0     11-1011.00  Chief Executives    2.C.1.a       IM        4.78
1     11-1011.00  Chief Executives    2.C.1.a       LV        6.50
2     11-1011.00  Chief Executives    2.C.1.b       IM        2.42
3     11-1011.00  Chief Executives    2.C.1.b       LV        2.69
4     11-1011.00  Chief Executives    2.C.1.c       IM        4.04

Great, lets take a quick look at our resultant dataframe

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 636301 entries, 0 to 289172
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   O*NET-SOC Code  636301 non-null  object
 1   Title           636301 non-null  object
 2   Element ID      636301 non-null  object
 3   Scale ID        636301 non-null  object
 4   Data Value      636301 non-null  float64
dtypes: float64(1), object(4)
memory usage: 29.1+ MB

In [27]:
print(f"We have a total of {df['O*NET-SOC Code'].nunique()} occupations and {df.groupby(['Element ID','Scale ID']).ngroup().nunique()} metrics")

We have a total of 923 occupations and 476 metrics

Lets edit the shape of this data to align with our vectorization task such that each occupation is a single row with solumns for each metric:

In [24]:
df_pivoted = df.pivot_table(index = ['O*NET-SOC Code'],
                           columns = ['Element ID', 'Scale ID'],
                           values = ['Data Value'])
df_pivoted.head()

               Data Value                                                  \
Element ID      1.A.1.a.1       1.A.1.a.2       1.A.1.a.3       1.A.1.a.4
Scale ID               IM    LV        IM    LV        IM    LV        IM
O*NET-SOC Code
11-1011.00           4.62  4.88      4.25  4.88      4.50  4.88      4.12
11-1011.03           4.00  4.62      4.00  4.25      4.00  4.75      4.12
11-1021.00           4.00  4.12      4.00  4.00      4.00  4.12      4.00
11-1031.00            NaN   NaN       NaN   NaN       NaN   NaN       NaN
11-2011.00           4.00  4.38      4.00  4.00      4.25  4.75      3.88

                                      ...                                      \
Element ID           1.A.1.b.1        ... 4.C.3.c.1         4.C.3.d.1
Scale ID          LV        IM    LV  ...        CX     CXP        CX     CXP
O*NET-SOC Code                        ...
11-1011.00      4.75      3.88  4.62  ...      3.57  20.000      4.16  20.000
11-1011.03      4.38      3.88  4.12  ...      3.70  20.000      3.48  20.000
11-1021.00      4.00      3.25  3.38  ...      3.37  19.998      4.08  20.002
11-1031.00       NaN       NaN   NaN  ...       NaN     NaN       NaN     NaN
11-2011.00      4.00      3.75  4.12  ...      3.34  20.000      4.40  20.000


Element ID     4.C.3.d.3         4.C.3.d.4            4.C.3.d.8
Scale ID              CX     CXP        CT        CTP        CT        CTP
O*NET-SOC Code
11-1011.00          1.35  20.000      1.09  33.330000      2.86  33.333333
11-1011.03          1.19  19.998      1.08  33.333333      2.74  33.333333
11-1021.00          1.19  20.002      1.16  33.333333      2.70  33.333333
11-1031.00           NaN     NaN       NaN        NaN       NaN        NaN
11-2011.00          1.00  20.000      1.20  33.333333      2.48  33.333333

[5 rows x 476 columns]